# Generated by Django 3.1.3 on 2020-12-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ScientificActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('PART_TIME_TEACHER', 'Part-time teacher'), ('FULL_TIME_TEACHER', 'Full-time teacher')], max_length=50)),
                ('s_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.scientificactivity')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ScientificWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('point', models.IntegerField(default=0)),
                ('term_date', models.DateField(default=0)),
                ('actual_date', models.DateField(default=0)),
                ('type', models.CharField(choices=[('SEMINAR', 'Seminar'), ('PUBLICATION', 'Publication')], max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('i_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.individualplan')),
            ],
        ),
        migrations.AddField(
            model_name='individualplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.user'),
        ),
    ]
